// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCEAPI.Data;

#nullable disable

namespace SCEventsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230216195452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SCEAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            Name = "Event 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Name = "Event 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            Name = "Event 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description 4",
                            Name = "Event 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description 5",
                            Name = "Event 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
